### ISSUE TITLE
Permission from Necrotic Gnome

### ISSUE THREAD

**Issue by gavinnorman** [Phenomen/ose#4]
Hey there,

Gavin from Necrotic Gnome here. I don't know of a better way to contact you.

I came across your Russian OSE SRD recently. Looks like really nice work! I just wanted to note that using the name Old-School Essentials on a product without my permission is (strictly speaking) not allowed. Would you like my permission?

Cheers!

**Comment by gavinnorman** [comment]
(Feel free to email summon@necroticgnome.com to chat if you like.)

**Comment by phenomen** [comment]
Hi Gavin! @gavinnorman 
I've already asked and you gave me permission to use Old-School Essentials name a long time ago: https://discord.com/channels/589023021856063497/589024464122150924/616327173783158831

> gavin: As long as you don't want to sell this, we can come to an agreement about using the OSE name

Is it still valid?

Thanks
